services:
  mysql:
    image: mysql:8
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
  python-app:
    image: python-app
    tty: true #Tells Docker to allocate a "teletypewriter" (a terminal screen).

    stdin_open: true #Tells the container to keep the "ear" open so it can hear what you type.
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - mysql

  

networks:
  my_network:
    driver: bridge

